name: Basic CI

on:
  push:
    branches: [main, setup-task]
  pull_request:
    branches: [main]

jobs:
  check-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Show Python version
        run: python --version

      - name: Install dependencies (if requirements.txt exists)
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi